version: '3'
services:
  app:
    image: 'hsts:latest'
    build:
      context: .
    container_name: hsts-app
    ports:
    - "8080:8080"
  nginx:
    image: 'hsts-nginx:latest'
    build:
      context: ./nginx
    container_name: hsts-nginx
    ports:
    - "80:80"
    - "443:443"
